@startuml Proxy

class Schtroumpf {
    saluer(animal: Animal): String
}

class SchtroumpfDouanier

Schtroumpf<|--SchtroumpfDouanier

class Animal {
    - name: String
}

class AnimalDangereux

Animal<|--AnimalDangereux

@enduml